# -*- coding: utf-8 -*-
{
    'name': 'University Registrar',
    'version': '1.0',
    'category': 'University',
    'summary': 'Manage student progression, freezing, expulsion, re-registration, results, and documents.',
    'depends': ['base', 'mail', 'account', 'university_core', 'university_student', 'university_curriculum', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/email_template_re_registration.xml',
        'wizard/freeze_otp_wizard_views.xml',
        'views/menu.xml',
        'views/freeze_request_views.xml',
        'views/unfreeze_request_views.xml',
        'views/student_extend_views.xml',
        'views/external_exam_views.xml',
        'views/document_request_views.xml',
        'views/timetable_template_views.xml',
        'report/resignation_reports.xml',
        'views/resignation_views.xml',
        'views/resignation_portal_templates.xml',
        'views/account_payment_views.xml',
        'data/email_template_resignation_otp.xml',
        'wizard/apply_template_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
}
