{
    'name': 'System 18 Fiscal Year & Lock Date',
    'version': '1.0.1',
    'category': 'Accounting',
    'summary': 'System 18 Fiscal Year, Fiscal Year in System 18, Lock Date in System 18',
    'description': 'System 18 Fiscal Year, Fiscal Year in System 18',
    'live_test_url': 'https://www.youtube.com/watch?v=Kj4hR7_uNs4',
    'sequence': '1',
    'website': 'https://www.odoomates.tech',
    'author': 'System Mates, System',
    'maintainer': 'System Mates',
    'license': 'LGPL-3',
    'support': 'odoomates@gmail.com',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/change_lock_date.xml',
        'views/fiscal_year.xml',
        'views/settings.xml',
    ],
    'images': ['static/description/banner.png'],
}
